import os
from building import *
from gcc import *
Import('rtconfig')

group = []

newlib_version = GetNewLibVersion(rtconfig)

if newlib_version and not GetDepend('RT_USING_EXTERNAL_LIBC'):
    print('Newlib version: ' + newlib_version)

    cwd = GetCurrentDir()
    src = Glob('*.c')

    CPPPATH = [cwd]
    CPPDEFINES = ['RT_USING_NEWLIBC', 'RT_USING_LIBC'] # do not set _POSIX_C_SOURCE; it hides ENOTSUP and wint_t on older newlib (gcc-arm-none-eabi 9.x)
    LIBS = ['c', 'm', 'gcc'] # link libc, libm, and libgcc (after objects, so __aeabi_* helpers resolve correctly)
    AddDepend(['RT_USING_NEWLIBC', 'RT_USING_LIBC'])

    group = group + DefineGroup('Compiler', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, LIBS = LIBS)

    list = os.listdir(cwd)
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
